name: Build N1 Armbian

on:
  workflow_dispatch:
    inputs:
      boards:
        description: "Comma delimited list"
        required: true
        default: "phicomm-n1"

      repository:
        description: "Packages from repository"
        required: true
        default: "yes"

env:
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Armbian build script
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: armbian/build
          path: build
          ref: master
          clean: false
      - name: Build beta images
        env:
          REBUILD_IMAGES: ${{ github.event.inputs.boards }}
          REPOSITORY: ${{ github.event.inputs.repository }}
        run: |
          cd build
          ./compile.sh
