name: Build N1 Armbian

on:
  workflow_dispatch:
    inputs:
      boards:
        description: "BOARD"
        required: true
        default: "lepotato"
env:
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Docker
        id: install
        run: |
          sudo timedatectl set-timezone "$TZ"
          sudo apt update
          sudo curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
      - name: Checkout Armbian build script
        id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: armbian/build
          path: build
          ref: master
          clean: false
      - name: Build Armbian in Docker
        id: build
        if: steps.install.outputs.status == 'success' && steps.checkout.outputs.status == 'success'
        run: |
          cd build
          sudo ./compile.sh docker BOARD=${{ github.event.inputs.boards }} BRANCH=current RELEASE=bullseye KERNEL_ONLY=yes KERNEL_CONFIGURE=no BUILD_MINIMAL=no BUILD_DESKTOP=no COMPRESS_OUTPUTIMAGE=yes
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
      - name: Upload Output
        uses: actions/upload-artifact@main
        if: steps.build.outputs.status == 'success'
        with:
          name: Armbian_${{ github.event.inputs.boards }}${{ env.FILE_DATE }}
          path: $GITHUB_WORKSPACE/Output
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3
