name: Build N1 Armbian

on:
  workflow_dispatch:
    inputs:
      boards:
        description: "BOARD"
        required: true
        default: "lepotato"
      branch:
        description: "BRANCH"
        required: true
        default: "current"
      release:
        description: "RELEASE"
        required: true
        default: "bullseye"
      kernelOnly:
        description: "KERNEL_ONLY"
        required: true
        default: "yes"
env:
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Init
        run: |
          sudo timedatectl set-timezone "$TZ"
      - name: Checkout Armbian build script
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: armbian/build
          path: build
          ref: master
          clean: false
      - name: Build Armbian
        id: build
        run: |
          if [ "${{ github.event.inputs.boards }}" != "phicomm-n1" ]; then
            echo "not phicomm-n1"
          fi
          cd build
          sudo ./compile.sh \
          BOARD=${{ github.event.inputs.boards }} \
          BRANCH=${{ github.event.inputs.branch }} \
          RELEASE=${{ github.event.inputs.release }} \
          KERNEL_ONLY=${{ github.event.inputs.kernelOnly }} \
          KERNEL_CONFIGURE=no \
          BUILD_MINIMAL=no \
          BUILD_DESKTOP=no \
          COMPRESS_OUTPUTIMAGE=yes
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
          echo "::set-output name=status::success"
          ls -laR $GITHUB_WORKSPACE/build/output
      - name: Upload output
        uses: actions/upload-artifact@main
        if: steps.build.outputs.status == 'success'
        with:
          name: Armbian_${{ github.event.inputs.boards }}${{ env.FILE_DATE }}
          path: ${GITHUB_WORKSPACE}/build/output
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3
